:tada: version 1.20210219

diff --git a/overlay/root/bin/install_zj2m b/overlay/root/bin/install_zj2m
--- a/overlay/root/bin/install_zj2m
+++ b/overlay/root/bin/install_zj2m
@@ -10,10 +10,12 @@ get_latest_release() {
   local tarball_url tarball
   tarball_url="$(curl -s https://api.github.com/repos/zwave-js/zwavejs2mqtt/releases/latest | grep tarball_url | cut -d : -f 2,3 | tr -d \",)"
   tarball="${workdir}/source.tar.gz"
+  echo -ne "\nDownloading latest release..."
   # shellcheck disable=SC2086
-  wget -O "${tarball}" ${tarball_url}
+  wget --quiet -O "${tarball}" ${tarball_url}
   tar -xzf "${tarball}" -C "${workdir}"
   cd "${workdir}"/*zwavejs2mqtt* || return 1
+  echo "  OK"
 }
 
 build_zj2m() {
@@ -38,27 +40,36 @@ build_zj2m() {
       store \
       stylesheets
   if [ -n "${updateDevices}" ]; then
-    git clone "${zwavejs}" \
-    rsync -av node-zwave-js/packages/config/config/devices/ './node_modules/@zwave-js/config/config/devices' \
-    rm -r -- node-zwave-js
+    git clone "${zwavejs}"
+    rsync -av node-zwave-js/packages/config/config/devices/ './node_modules/@zwave-js/config/config/devices'
+    rm -rf -- node-zwave-js
   fi
 }
 
-install_zj2m() {
+copy_zj2m() {
   local app_dir="${zwavejs2mqtt_app_dir}"
-  ## clean-up additional files and folders
-  find . -mindepth 1 -name '.*' -exec rm -r -- "{}" +
-  ## remove existing version
-  if [ -d "${app_dir}" ]; then
-    rm -r -- "${app_dir}"
+  ## remove all (dot) .files and .folders from zj2m build_src directory
+  find . -mindepth 1 -name '.*' -exec rm -rf -- "{}" +
+  ## if it's enabled and running, stop the zwavejs2mqtt service and set it to restart
+  if sysrc zwavejs2mqtt_enable &>/dev/null && service zwavejs2mqtt status &>/dev/null; then
+    local restart='YES'
+    service zwavejs2mqtt stop || err 1 "failed to stop service"
   fi
-  ## copy z2m build to app directory
+  ## if present, remove existing app directory
+  if [ -d "${app_dir}" ]; then
+    rm -rf -- "${app_dir}"
+  fi
+  ## install new app directory and copy zj2m build_src to it
   install -d -m 775 -- "${app_dir}" \
-  && cp -r . "${app_dir}"
+  && cp -Rf . "${app_dir}"
+  ## restart the service, if it was previously set to restart
+  if [ "${restart}" == 'YES' ]; then
+    service zwavejs2mqtt start
+  fi
 }
 
 get_latest_release \
 && build_zj2m \
-&& install_zj2m \
+&& copy_zj2m \
 || echo -e "\ninstall failed :("
-rm -r -- "${workdir}"
+rm -rf -- "${workdir}"
